server:
  AppVersion: 1.0.0
  Port: :8080
  PprofPort: :5555
  Mode: Development
  JwtSecretKey: secretkey
  CookieName: jwt-token
  ReadTimeout: 5
  WriteTimeout: 5
  CtxDefaultTimeout: 12
  CSRF: true
  Debug: false

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info

postgres:
  PostgresqlHost: 0.0.0.0
  PostgresqlPort: 5432
  PostgresqlUser: doston
  PostgresqlPassword: dostonlv
  PostgresqlDbname: task
  PostgresqlSslmode: false
  PgDriver: pgx
